### ISSUE TITLE
Error init CryptoPro в Trusted eSign 1.2.0 (UNIX).

### ISSUE THREAD

**Issue by nshdigt** [TrustedPlus/crypto#17]
Если сначала установить Trusted eSign 1.2.0, а потом установить ГОСТ сертификаты, то при запуске приложения:
1) в консоли возникает ошибка:
 Error init CryptoPro 
 Error: ProviderCryptopro Cannot be constructed ProviderCryptopro
../deps/wrapper/src/store/provider_cryptopro.cpp:15
init Error init CryptoPRO provider
../deps/wrapper/src/store/provider_cryptopro.cpp:54
init Error open store
../deps/wrapper/src/store/provider_cryptopro.cpp:44

2) в приложении не отображаются ГОСТ сертификаты

Помогает запуск скрипта fix_start_esign, который создает недостающие хранилища

**Comment by algv** [comment]
заменил флаги чтения хранилищ при инициализации: https://github.com/TrustedPlus/crypto/commit/7c7f1759a56b6ff4e3532f2a25a91c442a89017b
